//
//  Colors.swift
//  FlutterKeys
//
//  Created by Pheonix Clark on 6/29/24.
//

import SwiftUI
import AVFoundation

struct C0lors: View {
    let light = Color(hue: 0.1, saturation: 0.02, brightness: 0.8)
    let dark = Color(hue: 0.1, saturation: 0.02, brightness: 0.4)
    
    var body: some View {
        HStack{
            VStack{
                Rectangle()
                    .foregroundStyle(Color(light))
                Rectangle()
                    .foregroundStyle(Color(dark))
            }
            VStack{
                HStack{
                    Rectangle()
                        .foregroundStyle(Color(hue: 0, saturation: 0, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0, saturation: 0, brightness: 0.9))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0, saturation: 0, brightness: 0.8))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0, saturation: 0, brightness: 0.7))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0, saturation: 0, brightness: 0.6))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0, saturation: 0, brightness: 0.5))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0, saturation: 0, brightness: 0.4))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0, saturation: 0, brightness: 0.3))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0, saturation: 0, brightness: 0.2))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0, saturation: 0, brightness: 0.1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0, saturation: 0, brightness: 0))
                    
                }
                HStack{
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.1, saturation: 0, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.1, saturation: 0.1, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.1, saturation: 0.2, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.1, saturation: 0.3, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.1, saturation: 0.4, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.1, saturation: 0.5, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.1, saturation: 0.6, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.1, saturation: 0.7, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.1, saturation: 0.8, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.1, saturation: 0.9, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.1, saturation: 1, brightness: 1))
                    
                }
                HStack{
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.2, saturation: 0, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.2, saturation: 0.1, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.2, saturation: 0.2, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.2, saturation: 0.3, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.2, saturation: 0.4, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.2, saturation: 0.5, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.2, saturation: 0.6, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.2, saturation: 0.7, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.2, saturation: 0.8, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.2, saturation: 0.9, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.2, saturation: 1, brightness: 1))
                }
                HStack{
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.3, saturation: 0, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.3, saturation: 0.1, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.3, saturation: 0.2, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.3, saturation: 0.3, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.3, saturation: 0.4, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.3, saturation: 0.5, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.3, saturation: 0.6, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.3, saturation: 0.7, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.3, saturation: 0.8, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.3, saturation: 0.9, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.3, saturation: 1, brightness: 1))
                }
                HStack{
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.4, saturation: 0, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.4, saturation: 0.1, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.4, saturation: 0.2, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.4, saturation: 0.3, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.4, saturation: 0.4, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.4, saturation: 0.5, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.4, saturation: 0.6, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.4, saturation: 0.7, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.4, saturation: 0.8, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.4, saturation: 0.9, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.4, saturation: 1, brightness: 1))
                }
                HStack{
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.5, saturation: 0, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.5, saturation: 0.1, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.5, saturation: 0.2, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.5, saturation: 0.3, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.5, saturation: 0.4, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.5, saturation: 0.5, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.5, saturation: 0.6, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.5, saturation: 0.7, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.5, saturation: 0.8, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.5, saturation: 0.9, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.5, saturation: 1, brightness: 1))
                }
                HStack{
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.6, saturation: 0, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.6, saturation: 0.1, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.6, saturation: 0.2, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.6, saturation: 0.3, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.6, saturation: 0.4, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.6, saturation: 0.5, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.6, saturation: 0.6, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.6, saturation: 0.7, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.6, saturation: 0.8, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.6, saturation: 0.9, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.6, saturation: 1, brightness: 1))
                }
                HStack{
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.7, saturation: 0, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.7, saturation: 0.1, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.7, saturation: 0.2, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.7, saturation: 0.3, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.7, saturation: 0.4, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.7, saturation: 0.5, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.7, saturation: 0.6, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.7, saturation: 0.7, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.7, saturation: 0.8, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.7, saturation: 0.9, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.7, saturation: 1, brightness: 1))
                }
                HStack{
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.8, saturation: 0, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.8, saturation: 0.1, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.8, saturation: 0.2, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.8, saturation: 0.3, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.8, saturation: 0.4, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.8, saturation: 0.5, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.8, saturation: 0.6, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.8, saturation: 0.7, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.8, saturation: 0.8, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.8, saturation: 0.9, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.8, saturation: 1, brightness: 1))
                }
                HStack{
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.9, saturation: 0, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.9, saturation: 0.1, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.9, saturation: 0.2, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.9, saturation: 0.3, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.9, saturation: 0.4, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.9, saturation: 0.5, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.9, saturation: 0.6, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.9, saturation: 0.7, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.9, saturation: 0.8, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.9, saturation: 0.9, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 0.9, saturation: 1, brightness: 1))
                }
                HStack{
                    Rectangle()
                        .foregroundStyle(Color(hue: 1, saturation: 0, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 1, saturation: 0.1, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 1, saturation: 0.2, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 1, saturation: 0.3, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 1, saturation: 0.4, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 1, saturation: 0.5, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 1, saturation: 0.6, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 1, saturation: 0.7, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 1, saturation: 0.8, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 1, saturation: 0.9, brightness: 1))
                    Rectangle()
                        .foregroundStyle(Color(hue: 1, saturation: 1, brightness: 1))
                }
                


            }
        }
    }
}

#Preview {
    C0lors()
}
